version: '3'
services:
  minio:
    container_name: s3
    image: minio/minio:RELEASE.2022-03-17T06-34-49Z.fips
    environment:
      - MINIO_ROOT_USER=AKIAIOSFODNN7EXAMPLE
      - MINIO_ROOT_PASSWORD=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    command: server /data --console-address ":9001"
    ports:
      - '9000:9000'
      - '9001:9001'
  # configure minio on startup (create buckets, etc)
  # inspired by https://github.com/minio/minio/issues/4769
  # and         https://gist.github.com/haxoza/22afe7cc4a9da7e8bdc09aad393a99cc
  minio_init:
    container_name: s3_init
    image: minio/mc:RELEASE.2022-03-17T07-21-29Z
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add minio http://minio:9000 AKIAIOSFODNN7EXAMPLE wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY;
      /usr/bin/mc rb --force minio/cloud-wat-dev/;
      /usr/bin/mc mb minio/cloud-wat-dev/;
      /usr/bin/mc policy set public minio/cloud-wat-dev;
      /usr/bin/mc cp --recursive /example_data/ minio/cloud-wat-dev/;
      exit 0;
      "
    volumes:
      - ./example_data:/example_data
  wat-api:
    container_name: wat-api
    depends_on: 
      - minio_init
      - cache
      - sqs
    build: .
    restart: always
    environment:
      - WAT_API_SKIP_JWT=True
      - WAT_API_APP_PORT=8001
      - WAT_API_AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
      - WAT_API_AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      - WAT_API_AWS_DEFAULT_REGION=us-east-1
      - WAT_API_AWS_REGION=us-east-1
      - WAT_API_AWS_BUCKET=cloud-wat-dev
      - WAT_API_AWS_S3_REGION=us-east-1
      - WAT_API_AWS_S3_BUCKET=cloud-wat-dev
      - WAT_API_S3_MOCK=True
      - WAT_API_S3_BUCKET=cloud-wat-dev
      - WAT_API_S3_ENDPOINT=host.docker.internal:9000
      - WAT_API_S3_DISABLE_SSL=True
      - WAT_API_S3_FORCE_PATH_STYLE=True
    ports:
      - 8001:8001
    volumes:
      - ./:/workspaces
      - /var/run/docker.sock:/var/run/docker.sock