Starting: /go/bin/dlv dap --check-go-version=false --listen=127.0.0.1:36927 --log-dest=3 from /workspaces/wat-api/wat
DAP server listening at: 127.0.0.1:36927
Type 'dlv help' for list of commands.
target_plugin: hydrographscaler
plugin_image_and_tag: williamlehman/hydrographscaler:v0.0.1
model_configuration:
  model_name: hsm
  model_configuration_paths:
  - scheme: https
    authority: /model-library/hsm-Test
    fragment: hsm.json
model_links:
  linked_inputs: []
  required_outputs:
  - name: hsm1.csv
    parameter: flow
    format: .csv
event_config:
  output_destination:
    scheme: http
    authority: /minio/runs/realization_1/event_1
  realization:
    index: 1
    seed: 1234
  event:
    index: 1
    seed: 5678
  time_window:
    starttime: 2018-01-01T01:01:01.000000001Z
    endtime: 2020-12-31T01:01:01.000000001Z