model_configuration:
  model_name: Muncie
model_links:
  linked_inputs:
  - name: hsm1.csv
    parameter: flow
    format: csv
    resource_info:
      scheme: http
      authority: /minio/runs/realization_1/event_1
      fragment: hsm1.csv
  - name: Temp Project HDF File
    parameter: Project HDF File
    format: .hdf
    resource_info:
      scheme: https
      authority: /model-library/Muncie-Test
      fragment: muncie.p04.tmp.hdf
  - name: RAS B file
    parameter: B file stuff
    format: .b**
    resource_info:
      scheme: https
      authority: /model-library/Muncie-Test
      fragment: muncie.b04
  - name: RAS Project File
    parameter: Project Specification
    format: .prj
    resource_info:
      scheme: https
      authority: /model-library/Muncie-Test
      fragment: muncie.prj
  - name: RAS X File
    parameter: X File stuff
    format: .x**
    resource_info:
      scheme: https
      authority: /model-library/Muncie-Test
      fragment: muncie.x04
  - name: Event Configuration
    parameter: Event Specification
    format: .json
    resource_info:
      scheme: http
      authority: /minio/runs/realization_1/event_1
      fragment: EventConfiguration.json
  required_outputs:
  - name: muncie.p04.tmp.hdf
    parameter: ras p hdf file
    format: hdf
  - name: muncie.b04
    parameter: ras b file
    format: .b**
  - name: muncie.prj
    parameter: ras project file
    format: .prj
  - name: muncie.x04
    parameter: ras x file
    format: .x**